
name: test-and-lint
on: [push, workflow_call]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build
      run:  go build -v ./...

    - name: Test
      run:  go test -v ./... -coverprofile="coverage.out"
    
    - name: Lint
      uses: golangci/golangci-lint-action@v3.1.0
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Security and vulnerability analysis (CodeQL)
      uses: github/codeql-action/analyze@v2

    - name: Cache the CodeQL database
      uses: actions/cache@v3
      with:
        path: ~/.cache/codeql
        key: codeql-db-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          codeql-db-${{ github.ref }}-
          codeql-db-


    
