
name: test-and-lint
on: [push, workflow_call]

jobs:
  ci:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod # This will cache the Go modules
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run:  go build -v ./...

    - name: Test
      run:  go test -v ./... -coverprofile="coverage.out"
    
    - name: Lint
      uses: golangci/golangci-lint-action@v3.1.0      

    - name: Gosec Security Scanner
      run:  go install github.com/securego/gosec/v2/cmd/gosec@latest && gosec ./...
    
    - id: govulncheck # vulnerability check from go team https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
      uses: golang/govulncheck-action@v1
      with:
          go-version-input: 1.20.6
          go-package: ./...


    
