name: Node.js CI

on:
  push:

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x] # Define the Node.js version(s) you want to test against

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npx eslint . --ext .ts --fix

    - name: Build
      run: npm run build

    - name: Run tests
      run: npx jest

    # Optional: Upload test results as an artifact (if your test framework generates report files)
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always() # even if previous steps fail
      with:
        name: test-results
        path: path/to/your/test-results # Replace with the actual path to your test results