# build,test
name: Java CI with Maven

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '13' #{version}
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/org/example # Replace with your group ID to avoid caching your own artifacts
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # checkstyle plugin should be configured in pom.xml 
    # - name: Run Maven lint
    #   run: mvn checkstyle:check

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      run: mvn test --file pom.xml

    # Optional step to archive test results
    - name: Archive test results
      uses: actions/upload-artifact@v2
      if: always() # Run this step even if previous steps failed
      with:
        name: test-results
        path: '**/target/surefire-reports/*.xml'